database:
  host: localhost
  port: 5432
  user: ayush
  password: ""
  name: videocall
  sslmode: disable

jwt:
  secret: dev-secret-key
  expiration_hours: 24

websocket:
  allowed_origins:
    - http://localhost:3000
    - http://localhost:5173

server:
  port: 8080
  environment: development 